DROP SCHEMA IF EXISTS Modell CASCADE;

CREATE SCHEMA Modell;

SET search_path TO Modell;

CREATE TABLE A (
  B INTEGER PRIMARY KEY, 
  C INTEGER);

CREATE TABLE X (
  Y INTEGER PRIMARY KEY, 
  Z INTEGER);
			
CREATE TABLE U (
  B INTEGER REFERENCES A(B), 
  Y INTEGER REFERENCES X(Y), 
  W INTEGER, 
  PRIMARY KEY (B,Y));

GRANT USAGE ON SCHEMA Modell TO ilias;
GRANT SELECT ON ALL TABLES IN SCHEMA Modell TO ilias;

COMMIT;


